"""HTTP bridge: exposes the LangGraph agent and the scored corpus to the web UI.

Deliberately dumb wire format. This emits newline-delimited JSON events:

    {"type":"text",       "delta": "..."}
    {"type":"tool-start", "id": "...", "name": "ask_jev", "args": {...}}
    {"type":"tool-end",   "id": "...", "result": {...}}
    {"type":"error",      "message": "..."}
    {"type":"done"}

The Next.js route handler translates those into the AI SDK's UI message stream
using the SDK's own writer, so the wire format between browser and Next is
generated by the SDK rather than hand-rolled here. One less thing to get wrong.

Run:  uvicorn firehose.server:app --port 8000
"""
from __future__ import annotations

import hmac
import json
import os
import tomllib
from typing import Any, Iterator

from langchain_core.messages import AIMessage, AIMessageChunk

from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from .corpus import Corpus

CONFIG_PATH = os.environ.get("FIREHOSE_CONFIG", "config.toml")
MOCK = os.environ.get("FIREHOSE_MOCK", "").lower() in {"1", "true", "yes"}

# Shared secret between the Next server and this bridge. Optional for localhost
# development; REQUIRED once anything about this is reachable from the internet,
# because these endpoints spend real money on your behalf.
TOKEN = os.environ.get("FIREHOSE_TOKEN", "")

app = FastAPI(title="Firehose bridge")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[o for o in os.environ.get(
        "FIREHOSE_CORS", "http://localhost:3000,http://127.0.0.1:3000").split(",") if o],
    allow_methods=["*"],
    allow_headers=["*"],
)

_state: dict[str, Any] = {"agent": None, "saver": None, "corpus": None, "mtime": 0.0}


def require_token(authorization: str | None) -> None:
    """No-op when FIREHOSE_TOKEN is unset (local dev); enforced when it is set."""
    if not TOKEN:
        return
    expected = f"Bearer {TOKEN}"
    supplied = authorization or ""
    # constant-time compare so the token cannot be guessed a byte at a time
    if not hmac.compare_digest(supplied, expected):
        raise HTTPException(status_code=401, detail="bad or missing bridge token")


def _config() -> dict:
    with open(CONFIG_PATH, "rb") as fh:
        return tomllib.load(fh)


def _results_path() -> str:
    cfg = _config()
    return os.path.join(cfg.get("run", {}).get("output_dir", "out"), "results.jsonl")


def corpus() -> Corpus:
    """Reload when the scorer has written a newer file - runs are out of band."""
    path = _results_path()
    mtime = os.path.getmtime(path) if os.path.exists(path) else 0.0
    if _state["corpus"] is None or mtime != _state["mtime"]:
        _state["corpus"] = Corpus.from_jsonl(path)
        _state["mtime"] = mtime
        _state["agent"] = None          # rebuild so tools close over fresh data
    return _state["corpus"]


def agent() -> Any:
    c = corpus()
    if _state["agent"] is None:
        from .agent import build_agent

        cfg = _config()
        acfg = cfg.get("agent", {})
        a, saver = build_agent(
            c,
            backend=cfg.get("run", {}).get("backend", "aimlapi"),
            mock=MOCK,
            checkpoint_path=acfg.get("checkpoint_path", "state/agent.sqlite"),
            model=acfg.get("model"),
            base_url=acfg.get("base_url"),
            temperature=float(acfg.get("temperature", 0.3)),
        )
        _state["agent"], _state["saver"] = a, saver
    return _state["agent"]


# --------------------------------------------------------------------------
class ChatRequest(BaseModel):
    message: str
    thread: str = "web"


def _text_of(content: Any) -> str:
    """LLM chunk content is a string or a list of content blocks."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        out = []
        for block in content:
            if isinstance(block, str):
                out.append(block)
            elif isinstance(block, dict) and block.get("type") == "text":
                out.append(block.get("text", ""))
        return "".join(out)
    return ""


def _events(message: str, thread: str) -> Iterator[str]:
    def emit(obj: dict) -> str:
        return json.dumps(obj, default=str) + "\n"

    try:
        graph = agent()
    except Exception as exc:
        yield emit({"type": "error", "message": f"{exc}"})
        yield emit({"type": "done"})
        return

    config = {"configurable": {"thread_id": thread}}
    open_calls: dict[str, str] = {}
    try:
        for mode, payload in graph.stream(
            {"messages": [{"role": "user", "content": message}]},
            config=config,
            stream_mode=["updates", "messages"],
        ):
            if mode == "messages":
                chunk, _meta = payload
                # messages mode also replays ToolMessages - only the model's own
                # tokens belong in the assistant text stream
                if not isinstance(chunk, (AIMessageChunk, AIMessage)):
                    continue
                text = _text_of(getattr(chunk, "content", ""))
                if text:
                    yield emit({"type": "text", "delta": text})
            elif mode == "updates":
                for _node, update in (payload or {}).items():
                    for m in (update or {}).get("messages", []) or []:
                        for call in getattr(m, "tool_calls", None) or []:
                            cid = call.get("id") or call.get("name", "")
                            open_calls[cid] = call.get("name", "")
                            yield emit({"type": "tool-start", "id": cid,
                                        "name": call.get("name", ""),
                                        "args": call.get("args", {})})
                        if getattr(m, "type", "") == "tool" or m.__class__.__name__ == "ToolMessage":
                            cid = getattr(m, "tool_call_id", "")
                            raw = getattr(m, "content", "")
                            try:
                                result = json.loads(raw) if isinstance(raw, str) else raw
                            except json.JSONDecodeError:
                                result = raw
                            yield emit({"type": "tool-end", "id": cid,
                                        "name": open_calls.get(cid, ""), "result": result})
    except Exception as exc:
        yield emit({"type": "error", "message": f"{exc.__class__.__name__}: {exc}"})
    yield emit({"type": "done"})


@app.post("/api/chat")
def chat(req: ChatRequest, authorization: str | None = Header(default=None)) -> StreamingResponse:
    require_token(authorization)
    return StreamingResponse(
        _events(req.message, req.thread),
        media_type="application/x-ndjson",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.get("/api/stats")
def stats(authorization: str | None = Header(default=None)) -> dict:
    require_token(authorization)
    c = corpus()
    counts = c.counts()
    cfg = _config()
    return {
        **counts,
        "streams": {sid: s.get("name", sid) for sid, s in (cfg.get("streams") or {}).items()},
        "gates": cfg.get("gates", {}),
        "mock": MOCK,
        "updated": _state["mtime"],
    }


@app.get("/api/items")
def items(verdict: str = "keep", stream: str = "any", q: str = "", limit: int = 40,
          authorization: str | None = Header(default=None)) -> dict:
    require_token(authorization)
    rows = corpus().search(query=q, verdict=verdict, stream=stream, limit=min(limit, 200))
    return {"items": [r.full() for r in rows]}


@app.get("/api/health")
def health() -> dict:
    # deliberately unauthenticated so a load balancer or systemd check can use it;
    # it reveals nothing beyond liveness and a count
    return {"ok": True, "items": len(corpus()), "mock": MOCK, "auth": bool(TOKEN)}
